### ISSUE TITLE
JoinMode NONE not working as expected

### ISSUE THREAD

**Issue by jroucou** [rlespinasse/hoff#10]
```
ns.AddLink(action1, decision1)
ns.AddLink(action1, decision2)
ns.AddLinkOnBranch(decision1, action4, false)
ns.AddLinkOnBranch(decision2, action4, true)
ns.ConfigureJoinModeOnNode(action4, joinmode.NONE)
```
**computation report: map[decision2:'Continue on true' action4:'Continue' action1:'Continue' decision1:'Continue on true']**

action 4 is executed but it should not.

Only have this if one branch is on true and the other one on false.

**Comment by rlespinasse** [comment]
@jroucou the node system need to be invalid when X links use the the destination node (a.k.a `action4` in your case) without setup a join mode to `AND` or `OR`.
