### ISSUE TITLE
Node executed twice 

### ISSUE THREAD

**Issue by jroucou** [rlespinasse/hoff#11]
```
ns.AddLink(action1, decision1)
ns.AddLinkOnBranch(decision1, action2, true)
ns.AddLinkOnBranch(decision1, action3, false)
ns.AddLink(action2, action4)
ns.AddLink(action1, action4)
ns.ConfigureJoinModeOnNode(action4, joinmode.AND)
```

execution
```
action1
decision1
action2
action4
action4
```
=> same result with joinmode.OR

**Comment by rlespinasse** [comment]
@jroucou In case of a node with join mode `AND` (or `OR`), the node will be compute as many times a link point to it (in your case `2` times) but only need to be run once. In your case, when the `first` run occurs, the computation already have the computation state of `action1` and `action2` to decide if the node `action4` need to run. I add a check to avoid run twice the same node.
